# Usa imagem base oficial leve do Python
FROM python:3.10-slim

# Define diretório de trabalho
WORKDIR /app

# Instala ferramentas essenciais
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Copia dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia o código da aplicação
COPY . .

# Expor porta
EXPOSE 8000

# Executar a aplicação
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
